/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example06C_InformationFactory */

#ifndef _Included_example06C_InformationFactory
#define _Included_example06C_InformationFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example06C_InformationFactory
 * Method:    newInformationNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_example06C_InformationFactory_newInformationNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
