#pragma once

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example06_Information */

#ifndef _Included_example06_Information
#define _Included_example06_Information
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     example06_Information
	 * Method:    setInformation
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_example06_Information_setInformation
	(JNIEnv*, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
