#pragma once

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example06_Information */

#ifndef _Included_example06_InformationFactory
#define _Included_example06_InformationFactory
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     example06_InformationFactory
	 * Method:    newInformation
	 * Signature: ()Lexample06/Information;
	 */
	JNIEXPORT jobject JNICALL Java_example06_InformationFactory_newInformation
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
