/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example05_Mathematics */

#ifndef _Included_example05_Mathematics
#define _Included_example05_Mathematics
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     example05_Mathematics
	 * Method:    Addition
	 * Signature: (II)I
	 */
	JNIEXPORT jint JNICALL Java_example05_Mathematics_Addition
	(JNIEnv*, jobject, jint, jint);

	/*
	 * Class:     example05_Mathematics
	 * Method:    Subtraction
	 * Signature: (II)I
	 */
	JNIEXPORT jint JNICALL Java_example05_Mathematics_Subtraction
	(JNIEnv*, jobject, jint, jint);

	/*
	 * Class:     example05_Mathematics
	 * Method:    Multiplication
	 * Signature: (II)I
	 */
	JNIEXPORT jint JNICALL Java_example05_Mathematics_Multiplication
	(JNIEnv*, jobject, jint, jint);

	/*
	 * Class:     example05_Mathematics
	 * Method:    Division
	 * Signature: (II)I
	 */
	JNIEXPORT jint JNICALL Java_example05_Mathematics_Division
	(JNIEnv*, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
