/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example02_JNIExample02 */

#ifndef _Included_example02_JNIExample02
#define _Included_example02_JNIExample02
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     example02_JNIExample02
	 * Method:    doPrint
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_example02_JNIExample02_doPrint
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
