/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example06C_NativePointer */

#ifndef _Included_example06C_NativePointer
#define _Included_example06C_NativePointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example06C_NativePointer
 * Method:    make
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example06C_NativePointer_make
  (JNIEnv *, jobject);

/*
 * Class:     example06C_NativePointer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example06C_NativePointer_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
